# Generated by Django 3.0.2 on 2020-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('homemaker', 'homemaker'), ('customer', 'customer'), ('delivery', 'delivery')], default='customer', max_length=10),
        ),
    ]
