# Generated by Django 3.0.2 on 2020-01-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200123_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', related_query_name='profile', to='account.Address'),
        ),
    ]
