# Generated by Django 3.0.2 on 2020-01-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200130_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='profiles', related_query_name='profile', to='account.Address'),
        ),
    ]
