# Generated by Django 3.0.2 on 2020-01-30 18:03

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200130_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='kolkata', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default='nadia', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='flatNo',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='landmark',
            field=models.CharField(default='some land mark', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pinCode',
            field=models.IntegerField(default=828205, validators=[account.validators.ValidatePinCode]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='West Bengal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='mg road', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
