# Generated by Django 3.0.2 on 2020-01-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20200122_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', related_query_name='organisation', to='organisation.Menu'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/organisation/images/'),
        ),
    ]
