# Generated by Django 3.0.2 on 2020-01-26 14:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20200123_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='extra_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='extra_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organisation',
            name='facebook_page',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='instagram_page',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
