# Generated by Django 3.0.2 on 2020-01-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_auto_20200126_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='extra_available',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='stock',
        ),
    ]
