# Generated by Django 3.0.2 on 2020-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20200126_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='saturday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
