# Generated by Django 3.0.2 on 2020-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20200131_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='fssai_Lic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
