# Generated by Django 3.0.2 on 2020-01-23 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20200123_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(auto_now_add=True)),
                ('EndDate', models.DateField(default=datetime.date(2020, 1, 30))),
                ('weeks', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('subscribedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_to', to='account.Profile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='account.Profile')),
            ],
        ),
    ]
