# Generated by Django 3.0.2 on 2020-01-23 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(default=datetime.date(2020, 1, 23)),
        ),
    ]
