# Generated by Django 3.0.2 on 2020-01-23 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20200123_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
