# Generated by Django 3.0.2 on 2020-01-30 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20200129_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='EndDate',
            field=models.DateField(default=datetime.date(2020, 2, 6)),
        ),
    ]
