# Generated by Django 3.0.2 on 2020-01-31 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20200130_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='EndDate',
            field=models.DateField(default=datetime.date(2020, 2, 7)),
        ),
    ]
