# Generated by Django 3.0.2 on 2020-02-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20200131_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='EndDate',
            field=models.DateField(default=datetime.date(2020, 2, 13)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(default=datetime.date(2020, 2, 6)),
        ),
    ]
